CREATE TABLE `tb_vajra_position_publish` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `event_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '金刚位id',
  `vajra_position_id` bigint(10) NOT NULL COMMENT '金刚位id',
  `vajra_position_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `biz_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'marketing(营销), operation(运营)',
  `image_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '金刚位图片地址',
  `jump_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '跳转地址',
  `priority` int(11) NOT NULL COMMENT '金刚位优先级',
  `target_page_ids` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'json数组格式，适配页面id列表',
  `start_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '开始版本',
  `end_version` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '截止版本',
  `validity_period_start` timestamp NOT NULL DEFAULT '1970-12-31 17:00:00' COMMENT '有效期起始时间',
  `validity_period_end` timestamp NOT NULL DEFAULT '1970-12-31 17:00:00' COMMENT '有效期结束时间',
  `platform_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'android,ios,all',
  `user_id_tail_range_start` int(11) DEFAULT NULL COMMENT '用户尾数范围起始',
  `user_id_tail_range_end` int(11) DEFAULT NULL COMMENT '用户尾数范围结束',
  `user_bizId_range_start` int(11) DEFAULT NULL COMMENT '用户bizId范围开始',
  `user_bizId_range_end` int(11) DEFAULT NULL COMMENT '用户bizId范围结束',
  `white_list_id` bigint(10) DEFAULT NULL COMMENT 'uid名单表id',
  `exclude_conditions` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '排除人群条件，json数组格式',
  `version` int(11) NOT NULL COMMENT '版本号',
  `status` int(11) NOT NULL COMMENT '启用（1）或禁用（0）',
  `publisher_id` bigint(10) NOT NULL COMMENT '发布人员id',
  `inserttime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `updatetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isactive` tinyint(1) DEFAULT '1' COMMENT '逻辑删除',
  `anon_visible` tinyint(1) NOT NULL DEFAULT '1' COMMENT '未登录用户是否可见',
  `login_visible` tinyint(1) NOT NULL DEFAULT '1' COMMENT '登录用户是否可见',
  `pms_decision` tinyint(1) DEFAULT '0' COMMENT '是否需要PMS决策，0否，1是',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='金刚位配置表发布';