druid:
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall,log4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  useGlobalDataSourceStat: true

datasource:
  one:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drools_test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root


spring:
  application:
    name: unit-test-github
  redis:
    host: r-3nsipq2qrjdaj7j7uv.redis.rds.aliyuncs.com
    port: 6379
    password: t5muQo1VNsDenOm
    timeout: 6000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 5
        max-wait: 1000ms
        min-idle: 0
